import { StyleSheet } from 'react-native';
import { Theme } from '../../../../../styles/globalTheme/theme';

export const createPopupFormStyles = (theme: Theme) => {
  const colors = {
    overlay: 'rgba(0, 0, 0, 0.5)',
    borderDefault: theme.colors.border,
    backgroundPopup: theme.colors.Foreground,
    textPrimary: theme.colors.textPrimary,
    textError: theme.colors.error,
    textSecondary: theme.colors.textSecondary,
    borderError: theme.colors.error,
    backgroundSecondary: theme.colors.userInput,
    borderGray: theme.colors.border,
    accentRedTransparent: theme.colors.cancelAccent + 'ea',
    cancelButtonBorder: theme.colors.border,
    confirmButtonBg: theme.colors.confirmAccent2,
    cancelButtonBg: theme.colors.cancelAccent2,
  };
  return StyleSheet.create({
    overlayContainer: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.overlay,
      zIndex: 1,
    },
    popUpMenu: {
      gap: 5,
      paddingVertical: 20,
      borderWidth: 1,
      borderColor: colors.borderDefault,
      backgroundColor: colors.backgroundPopup,
      position: 'absolute',
      justifyContent: 'center',
      width: '80%',
      height: 'auto',
      borderRadius: theme.borderRads.m,
    },
    overlayLabel: {
      color: colors.textPrimary,
      fontSize: 16,
      paddingLeft: 15,
      paddingBottom: 5,
    },
    overlayLabelErr: {
      color: colors.textError,
      fontSize: 16,
      paddingLeft: 15,
      paddingBottom: 5,
    },
    Label: {
      color: colors.textSecondary,
      fontSize: 16,
      paddingLeft: 15,
    },
    subjectSelectError: {
      display: 'flex',
      borderRadius: 8,
      width: 132,
      height: 42,
      backgroundColor: colors.borderError,
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    subjectSelect: {
      width: 132,
      height: 42,
      backgroundColor: '#0000',
      borderRadius: 8,
      justifyContent: 'center',
      display: 'flex',
      alignContent: 'center',
      alignItems: 'center',
    },
    inputErrorFeed: {
      color: colors.borderError,
      fontSize: 14,
      paddingLeft: 15,
    },
    userInput: {
      backgroundColor: colors.backgroundSecondary,
      color: colors.textPrimary,
      paddingLeft: 10,
      alignSelf: 'center',
      borderRadius: theme.borderRads.m,
      width: '90%',
      borderWidth: 1,
      borderColor: colors.borderDefault,
    },
    userInputFocused: {
      backgroundColor: colors.backgroundSecondary,
      color: colors.textPrimary,
      paddingLeft: 10,
      alignSelf: 'center',
      borderRadius: theme.borderRads.m,
      width: '90%',
      borderWidth: 1,
      borderColor: colors.borderDefault,
      outlineColor: colors.borderGray,
      outlineWidth: 4,
    },
    userInputFocusedError: {
      backgroundColor: colors.backgroundSecondary,
      color: colors.textPrimary,
      paddingLeft: 10,
      alignSelf: 'center',
      borderRadius: theme.borderRads.m,
      width: '90%',
      borderWidth: 1,
      borderColor: colors.borderDefault,
      outlineColor: colors.accentRedTransparent,
      outlineWidth: 4,
    },
    invalidUserInput: {
      backgroundColor: colors.backgroundSecondary,
      color: colors.textPrimary,
      paddingLeft: 10,
      alignSelf: 'center',
      borderRadius: theme.borderRads.m,
      width: '90%',
      borderWidth: 1,
      borderColor: colors.borderError,
    },
    confirmButton: {
      alignSelf: 'center',
      marginBottom: '2%',
      marginTop: '2%',
      width: '80%',
      height: 50,
      backgroundColor: colors.confirmButtonBg,
      borderRadius: theme.borderRads.m,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelButton: {
      alignSelf: 'center',
      marginBottom: '2%',
      marginTop: '2%',
      width: '80%',
      height: 50,
      backgroundColor: colors.cancelButtonBg,
      borderRadius: theme.borderRads.m,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.cancelButtonBorder,
    },
    buttonText: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },
  });
};
